function numberedCases(prefix, start, end, family) {
  return Array.from({ length: end - start + 1 }, (_, index) => ({
    id: `${prefix}${String(start + index).padStart(2, '0')}`,
    family,
  }));
}

export const ACCESS_CASE_CATALOG = Object.freeze([
  ...numberedCases('TC-AR-', 1, 6, 'Core functional'),
  ...numberedCases('TC-AR-B', 1, 8, 'Conditional branches'),
  ...numberedCases('TC-AR-R', 1, 4, 'Recovery'),
  ...numberedCases('TC-AR-U', 1, 7, 'Uploads'),
  ...numberedCases('TC-AR-P', 1, 5, 'Person context'),
  ...numberedCases('TC-AR-D', 1, 4, 'Document context'),
  ...numberedCases('TC-AR-S', 1, 4, 'Site search'),
  ...numberedCases('TC-AR-C', 1, 8, 'Copy and reuse'),
  ...numberedCases('TC-AR-E', 1, 10, 'Efficiency'),
  ...numberedCases('TC-AR-A', 1, 5, 'Accessibility and responsive'),
  ...numberedCases('TC-AR-X', 1, 3, 'Cross-workflow'),
]);

export const STEPS_5_TO_8_CASE_IDS = Object.freeze([
  'TC-AR-005',
  'TC-AR-006',
  'TC-AR-B03',
  'TC-AR-B05',
  'TC-AR-B06',
  'TC-AR-B08',
  'TC-AR-R01',
  'TC-AR-R02',
  'TC-AR-R03',
  'TC-AR-R04',
  'TC-AR-U01',
  'TC-AR-U02',
  'TC-AR-U03',
  'TC-AR-U04',
  'TC-AR-U05',
  'TC-AR-U06',
  'TC-AR-U07',
  'TC-AR-D01',
  'TC-AR-D02',
  'TC-AR-D03',
  'TC-AR-D04',
  'TC-AR-E01',
  'TC-AR-E02',
  'TC-AR-E03',
  'TC-AR-E04',
  'TC-AR-E05',
  'TC-AR-E06',
  'TC-AR-E07',
  'TC-AR-E08',
  'TC-AR-E09',
  'TC-AR-E10',
  'TC-AR-A01',
  'TC-AR-A02',
  'TC-AR-A03',
  'TC-AR-A04',
  'TC-AR-A05',
]);
